stages:
  - build
  - test

build tests and executable:
  stage: build
  tags:
    - 'dw-builder' 
  only: 
    - main

  script:
    - git submodule init
    - git submodule update
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DWITH_UNIT_TEST=1 ..
    - make -j 2

  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 1 day

# run tests using the binary built before
test programs:
  stage: test
  tags:
    - 'dw-builder' 
  only:
      - main
  dependencies:
    - build tests and executable 
  script:
      - cd build
      - make test
      - cd ../tests/integrationTests
      - ./run_all_tests.sh
      - cd ../../build
      - gcovr -f ../src/
  coverage: '/\d*\.*\d+%/'

### GITLAB SECURITY TESTS ###

services:
  - docker:20.10.21-dind

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  tags:
    - 'dind'

code_quality:
  services:
  tags:
    - 'dind'
  artifacts:
    paths: [gl-code-quality-report.json]

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

sast:
  tags:
    - "dind"
  stage: test

pages:
  stage: deploy
  script:
  - cd docs
  - make gitlab-pages
  artifacts:
    paths:
    - public
  only:
  - master
