stages:
  - build
  - test


build tests and executable:
  stage: build
  only: 
    - main

  script:
    - git submodule init
    - git submodule update
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DWITH_UNIT_TEST=1 ..
    - make -j 2

  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 1 day

# run tests using the binary built before
test programs:
  stage: test
  only:
      - main
  dependencies:
    - build tests and executable 
  script:
      - cd build
      - make test
      - cd ../tests/integrationTests
      - ./run_all_tests.sh
      - gcovr -f ../../src/
  coverage: '/\d*\.*\d+%/'

        
